name: Build & Publish
on:
  push:
    branches:
      - master
      - alpha
      - beta
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish Pre-Release
        if: github.ref == 'refs/heads/alpha' || github.ref == 'refs/heads/beta'
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
